module "gcs_bucket" {
  source            = "./module"
  bucket_name       = var.bucket_name
  location          = var.location
  project_id        = var.project_id
  force_destroy     = var.force_destroy
  versioning        = var.versioning
  uniform_access    = var.uniform_access
  labels            = var.labels
  log_bucket        = var.log_bucket
  log_object_prefix = var.log_object_prefix
  lifecycle_age     = var.lifecycle_age
  kms_key_name      = var.kms_key_name
  retention_period  = var.retention_period
  storage_class     = var.storage_class
  objects           = var.objects
  empty_file_path   = var.empty_file_path
  content_type      = var.content_type
  cache_control     = var.cache_control
  object_metadata   = var.object_metadata
}
